### ISSUE TITLE
Rename the repository?

### ISSUE THREAD

**Issue by abitmore** [denkhaus/go-bitshares#33]
Thanks for your efforts maintaining the library. However, it is a bit confusing that the repository is simply named "bitshares". Perhaps rename it to "go-bitshares"? Note there is another Go library for BitShares: https://github.com/scorum/bitshares-go although I'm not sure what's the status.

**Comment by denkhaus** [comment]
Why not. renamed!

**Comment by abitmore** [comment]
Thanks. Updated https://github.com/bitshares/awesome-bitshares.
