### ISSUE TITLE
I think this is a CBC Padding error

### ISSUE THREAD

**Issue by Brochao** [denkhaus/go-bitshares#35]
https://github.com/denkhaus/go-bitshares/blob/1874c0d6dcdb944bc9bfb84b0cff06560dc32f4d/types/memo.go#L66

I believe there's no need to determine whether the length is an integer multiple of 16，cause padding is still needed even if length is 16.

it should be like this

//if len(raw)%16 != 0 {
  raw = pad(raw, 16)
 //}

**Comment by Brochao** [comment]
you can try :
when memo plain's length equals 12, the cipher cannot be decrypted if you don't comment out the code.

**Comment by denkhaus** [comment]
fixed by commit 27e9ff5
